# https://docs.readthedocs.io/en/latest/yaml-config.html

build:
  image: latest  # For python 3.6

submodules:
  include: all
  recursive: true

formats:
    - epub
    - pdf

python:
    version: 3.6
    
requirements_file: 
    requirements/eequirements_doc.txt
